version: 2
updates:
  - package-ecosystem: "github-actions"
    assignees:
      - "kernelsam"
    cooldown:
      default-days: 21
      exclude:
        - "senzing-factory/*"
    directory: "/"
    groups:
      senzing-factory:
        patterns:
          - "senzing-factory/*"
    schedule:
      interval: "daily"
  - package-ecosystem: "nuget"
    assignees:
      - "barrycaceres"
    cooldown:
      default-days: 21
    directories:
      - /Senzing.Sdk.Demo/
      - /Senzing.Sdk.TestHelpers/
      - /Senzing.Sdk.Tests/
      - /Senzing.Sdk/
    schedule:
      interval: "daily"
